spring:
  profiles:
    active: test

springdoc:
  auto-tag-classes: true
  show-actuator: true
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  swagger-ui:
    path: /swagger-ui.html